title: "Nikhil Raghavendra"
description: "Studying intelligence, artificial and otherwise"
url: "https://nikhilr.io"
baseurl: ""
timezone: Asia/Singapore
permalink: /posts/:title/
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/page:num/"

navigation:
  - name: Home
    url: /
  - name: About
    url: /about

author: Nikhil Raghavendra

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Nikhil Raghavendra"
      excerpt_separator: "<!--more-->"
